/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import Conexion.CategoriasData;
import Conexion.ProductoData;
import Entidades.Producto;
import Entidades.Variables;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Objects;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gonza
 */
public class Productos extends javax.swing.JInternalFrame {

    ProductoData prod = new ProductoData();
    CategoriasData cate = new CategoriasData();
    private DefaultTableModel modelo = new DefaultTableModel() {
        public boolean isCellEditable(int fila, int columna) {
            if (columna == 0) {
                return false;
            } else {
                return true;
            }
        }
    };

    public Productos() {
        initComponents();
        listaCombo();
        litaTabla();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTLista = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jClista = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setText("Gesion de productos");

        jLabel2.setText("Categoria");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTLista);

        jButton2.setText("Crear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jClista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClistaActionPerformed(evt);
            }
        });

        jButton5.setText("Salir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        Escritorio1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio1.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio1.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio1.setLayer(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio1.setLayer(jClista, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio1.setLayer(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout Escritorio1Layout = new javax.swing.GroupLayout(Escritorio1);
        Escritorio1.setLayout(Escritorio1Layout);
        Escritorio1Layout.setHorizontalGroup(
            Escritorio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Escritorio1Layout.createSequentialGroup()
                .addGap(0, 506, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(49, 49, 49))
            .addGroup(Escritorio1Layout.createSequentialGroup()
                .addGroup(Escritorio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Escritorio1Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Escritorio1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jClista, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Escritorio1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Escritorio1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jButton2)
                        .addGap(40, 40, 40)
                        .addComponent(jButton3)
                        .addGap(47, 47, 47)
                        .addComponent(jButton4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Escritorio1Layout.setVerticalGroup(
            Escritorio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Escritorio1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(76, 76, 76)
                .addGroup(Escritorio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jClista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(Escritorio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Escritorio1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Escritorio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int id = Integer.parseInt(jClista.getItemAt(jClista.getSelectedIndex()).split(" - ")[0]);
        modelo.setRowCount(0);

        for (Producto pro : prod.listarProductosActivos(id)) {
            modelo.addRow(new Object[]{pro.getIdProducto(), pro.getNombreProducto(), pro.getImportadonacional(), pro.getDescripcion(),
                pro.getFechalimite(), pro.getPrecioActual(), pro.getStock()});
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int selec = jTLista.getSelectedRow();

        if (selec != -1) {
            int id = Integer.parseInt(jClista.getItemAt(jClista.getSelectedIndex()).split(" - ")[0]);
            int idp = (Integer) jTLista.getValueAt(selec, 0);
            String nombre = Objects.toString(jTLista.getValueAt(selec, 1), "");
            String importado = Objects.toString(jTLista.getValueAt(selec, 2), "");
            String descri = Objects.toString(jTLista.getValueAt(selec, 3), "");
            String FechaLimite = Objects.toString(jTLista.getValueAt(selec, 4), "");
            String precio = Objects.toString(jTLista.getValueAt(selec, 5), "");
            String stock = Objects.toString(jTLista.getValueAt(selec, 6), "");
            LocalDate fechaLimite = LocalDate.parse(FechaLimite, DateTimeFormatter.ofPattern("yyyy-MM-dd"));

            try {
                int Stock = Integer.parseInt(stock);
                double Precio = Double.parseDouble(precio);

                Producto produc = new Producto(idp,id, nombre, importado, descri, fechaLimite, Precio, Stock, true);
                prod.modificarProducto(produc);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Complete con datos válidos ");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una fila para modificar.");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CrearProducto Cprod = new CrearProducto();
        Cprod.setVisible(true);
        Escritorio1.add(Cprod);
        Escritorio1.moveToFront(Cprod);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jClistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jClistaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        int selec = jTLista.getSelectedRow();
        if (selec != 1) {
            int id = (Integer) jTLista.getValueAt(selec, 0);
            prod.eliminarProductoEstado(id);
            modelo.removeRow(selec);
        }
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jClista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTLista;
    // End of variables declaration//GEN-END:variables
     private void listaCombo() {

        for (Variables prod : cate.listarCategoria()) {
            jClista.addItem(prod.getIdCategoria() + " - " + prod.getnombreCategoria());
        }
    }

    private void litaTabla() {
        modelo.addColumn("idProducto");
        modelo.addColumn("nombreProducto");
        modelo.addColumn("importado/nacional");
        modelo.addColumn("descripcion");
        modelo.addColumn("fechaLimite");
        modelo.addColumn("precioActual");
        modelo.addColumn("stock");
        jTLista.setModel(modelo);

    }
}
