/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import java.util.ArrayList;
import Conexion.ProveedorData;
import Entidades.Proveedor;
import java.util.Objects;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gonza
 */
public class Proveedores extends javax.swing.JInternalFrame {

    ProveedorData provD = new ProveedorData();
    private DefaultTableModel modelo = new DefaultTableModel() {
        public boolean isCellEditable(int fila, int columna) {
            if (columna == 0) {
                return false;
            } else {
                return true;
            }
        }
    };

    /**
     * Creates new form Proveedores
     */
    public Proveedores() {
        initComponents();
        listaCombo();
        ProveedorTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EscritProveedor = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTLista = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jCProveedores = new javax.swing.JComboBox<>();
        jButton8 = new javax.swing.JButton();

        setClosable(true);

        jTLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idProveedor", "razonSocial", "domicilio", "telefono", "email", "paginaWeb"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTLista);
        if (jTLista.getColumnModel().getColumnCount() > 0) {
            jTLista.getColumnModel().getColumn(0).setResizable(false);
        }

        jButton6.setText("limpiar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton5.setText("Listar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Gestion de proveedores");

        jLabel2.setText("Buscar por rason social");

        jButton2.setText("Agregar Proveedor");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton7.setText("Salir");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Salir");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        EscritProveedor.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EscritProveedor.setLayer(jButton6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EscritProveedor.setLayer(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EscritProveedor.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EscritProveedor.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EscritProveedor.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EscritProveedor.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EscritProveedor.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EscritProveedor.setLayer(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EscritProveedor.setLayer(jButton7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EscritProveedor.setLayer(jCProveedores, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EscritProveedor.setLayer(jButton8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout EscritProveedorLayout = new javax.swing.GroupLayout(EscritProveedor);
        EscritProveedor.setLayout(EscritProveedorLayout);
        EscritProveedorLayout.setHorizontalGroup(
            EscritProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EscritProveedorLayout.createSequentialGroup()
                .addGroup(EscritProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, EscritProveedorLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(351, 351, 351))
                    .addGroup(EscritProveedorLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton7)))
                .addGap(16, 16, 16))
            .addGroup(EscritProveedorLayout.createSequentialGroup()
                .addGap(637, 637, 637)
                .addComponent(jButton5)
                .addGap(0, 89, Short.MAX_VALUE))
            .addGroup(EscritProveedorLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(EscritProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EscritProveedorLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EscritProveedorLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jCProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jButton1)))
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EscritProveedorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(65, 65, 65))
            .addGroup(EscritProveedorLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jButton2)
                .addGap(68, 68, 68)
                .addComponent(jButton3)
                .addGap(57, 57, 57)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addGap(82, 82, 82))
        );
        EscritProveedorLayout.setVerticalGroup(
            EscritProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscritProveedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(EscritProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EscritProveedorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(EscritProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jCProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)
                        .addGap(18, 18, 18)
                        .addGroup(EscritProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addComponent(jButton7)
                        .addGap(89, 89, 89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EscritProveedorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton8)
                        .addGap(182, 182, 182))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 7, Short.MAX_VALUE)
                .addComponent(EscritProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addComponent(EscritProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int selec = jTLista.getSelectedRow();
                String razonSocial = Objects.toString(jTLista.getValueAt(selec, 1), "");
                String domicilio = Objects.toString(jTLista.getValueAt(selec, 2), "");
                String telefono = Objects.toString(jTLista.getValueAt(selec, 3), "");
        if (selec != 1) {
            if ( razonSocial.trim().isEmpty()||domicilio.trim().isEmpty()||telefono.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Complete con datos correctamente.");
            } else {
                int idp = (Integer) jTLista.getValueAt(selec, 0);
               
                String email = Objects.toString(jTLista.getValueAt(selec, 4), "");
                String pagina = Objects.toString(jTLista.getValueAt(selec, 5), "");
                try {
                    int Telefono = Integer.parseInt(telefono);
                    Proveedor prove = new Proveedor(idp, razonSocial, domicilio, Telefono, email, pagina);
                    provD.modificarProveedor(prove);

                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Complete con datos válidos el campo teléfono.");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una fila antes de presionar el boton.");
        }
        jCProveedores.removeAllItems();
         listaCombo();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        CrearProveedor crearP = new CrearProveedor();
        crearP.setVisible(true);
        EscritProveedor.add(crearP);
        EscritProveedor.moveToFront(crearP);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        modelo.setRowCount(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        modelo.setRowCount(0);
        for (Proveedor prove : provD.listarProveedores()) {
            modelo.addRow(new Object[]{prove.getIdProveedor(), prove.getRazonSocial(), prove.getDomicilio(), prove.getTelefono(), prove.getEmail(),
                prove.getPagina()});
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int id = Integer.parseInt(jCProveedores.getItemAt(jCProveedores.getSelectedIndex()).split(" - ")[0]);

        modelo.setRowCount(0);
        Proveedor prove = provD.buscarProveedor(id);
        modelo.addRow(new Object[]{prove.getIdProveedor(), prove.getRazonSocial(), prove.getDomicilio(), prove.getTelefono(), prove.getEmail(),
            prove.getPagina()});

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        int selec = jTLista.getSelectedRow();
        if (selec != 1) {
            int idP = (Integer) jTLista.getValueAt(selec, 0);
            provD.eliminarProveedor(idP);
            modelo.removeRow(selec);
            jCProveedores.removeAllItems();
            listaCombo();
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane EscritProveedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jCProveedores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTLista;
    // End of variables declaration//GEN-END:variables
    private void listaCombo() {

        for (Proveedor prove : provD.listarProveedores()) {
            jCProveedores.addItem(prove.getIdProveedor() + " - " + prove.getRazonSocial());
        }
    }

    private void ProveedorTabla() {
        modelo.addColumn("idProveedor");
        modelo.addColumn("razonSocial");
        modelo.addColumn("domicilio");
        modelo.addColumn("telefono");
        modelo.addColumn("email");
        modelo.addColumn("paginaWeb");
        jTLista.setModel(modelo);

    }

    public static boolean validarDatos(String datos) {
        return datos.matches("[0-9]");
    }

}
