/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import Conexion.CategoriasData;
import Entidades.Variable2;
import Entidades.Variables;



/**
 *
 * @author gonza
 */
public class Variables1 extends javax.swing.JInternalFrame {
       CategoriasData categoriasData = new CategoriasData ();
     
 
    /**
     * Creates new form Variables
     */
    public Variables1() {
        initComponents();
        cargarLista ();
        cargarMetodos();
    }

    
     
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCcategoria = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTCategorias = new javax.swing.JTextField();
        jBCrear = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTMetodo = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jCMetodo = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jTNuevoDato = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTNuevoMetodo = new javax.swing.JTextField();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(750, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Categorias");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 23, 75, -1));

        jCcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCcategoriaActionPerformed(evt);
            }
        });
        jPanel1.add(jCcategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 190, -1));

        jLabel2.setText("Elegir categoria");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        jLabel3.setText("Nueva categoria");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 60, 89, -1));
        jPanel1.add(jTCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 57, 143, -1));

        jBCrear.setText("Crear");
        jBCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrearActionPerformed(evt);
            }
        });
        jPanel1.add(jBCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        jBModificar.setText("Modificar");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });
        jPanel1.add(jBModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, -1, -1));

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, -1, -1));

        jLabel4.setText("Cambio");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 65, -1));

        jLabel5.setText("Valor Actual");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 65, -1));

        jTextField2.setEditable(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 80, -1));

        jLabel6.setText("Nuevo Valor");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel7.setText("Metodos de Pago");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 137, -1));

        jLabel8.setText("Nuevo Metodo");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jTMetodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTMetodoActionPerformed(evt);
            }
        });
        jPanel1.add(jTMetodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 140, -1));

        jButton4.setText("Crear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, -1, -1));

        jLabel9.setText("Elegir Metodo");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 81, -1));

        jCMetodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCMetodoActionPerformed(evt);
            }
        });
        jPanel1.add(jCMetodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 190, -1));

        jButton5.setText("Modificar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, -1, -1));

        jButton6.setText("Eliminar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, -1, -1));

        jButton7.setText("Salir");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, -1, -1));

        jTNuevoDato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNuevoDatoActionPerformed(evt);
            }
        });
        jPanel1.add(jTNuevoDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 190, -1));

        jLabel10.setText("Ingrese nuevo dato : ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 110, 20));

        jLabel11.setText("Ingrese nuevo dato:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, -1, -1));

        jTNuevoMetodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNuevoMetodoActionPerformed(evt);
            }
        });
        jPanel1.add(jTNuevoMetodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 190, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
    String id = jCcategoria.getItemAt(jCcategoria.getSelectedIndex()).split(" - ")[0];
    int idc = Integer.parseInt(id);
    String nuevoDato = jTNuevoDato.getText();
    Variables vari = new Variables(idc,nuevoDato);
    categoriasData.modificarCategoria(vari);
    
    
    }//GEN-LAST:event_jBModificarActionPerformed

    private void jBCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCrearActionPerformed
        String catego = jTCategorias.getText();
        Variables variable = new Variables(catego);
        categoriasData.guardarCategoria(variable);
        
    }//GEN-LAST:event_jBCrearActionPerformed

    private void jCcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCcategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCcategoriaActionPerformed

    private void jTNuevoDatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNuevoDatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNuevoDatoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    String id = jCcategoria.getItemAt(jCcategoria.getSelectedIndex()).split(" - ")[0];
    int idc = Integer.parseInt(id);   
        categoriasData.borrarCategoria(idc);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTMetodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTMetodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTMetodoActionPerformed

    private void jCMetodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCMetodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCMetodoActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       String Nombre = jTMetodo.getText();
       Variable2 variable = new Variable2 (Nombre);
       categoriasData.guardarMetodos(variable);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       String id = jCMetodo.getItemAt(jCMetodo.getSelectedIndex()).split(" - ")[0];
        int idc = Integer.parseInt(id);
        String nuevoDato = jTNuevoMetodo.getText();
        Variable2 vari = new Variable2(idc,nuevoDato);
        categoriasData.modificarMetodo(vari);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTNuevoMetodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNuevoMetodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNuevoMetodoActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    String id = jCMetodo.getItemAt(jCMetodo.getSelectedIndex()).split(" - ")[0];
    int idc = Integer.parseInt(id);   
    categoriasData.borrarMetodoPago(idc);
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCrear;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jCMetodo;
    private javax.swing.JComboBox<String> jCcategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTCategorias;
    private javax.swing.JTextField jTMetodo;
    private javax.swing.JTextField jTNuevoDato;
    private javax.swing.JTextField jTNuevoMetodo;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
    private void cargarLista (){
        
        for (Variables var : categoriasData.listarCategoria()) {
            jCcategoria.addItem(var.getIdCategoria() + " - " + var.getnombreCategoria());
        }
            
        
    }
    private void cargarMetodos(){
        for (Variable2 var : categoriasData.listarMetodos()){
            jCMetodo.addItem(var.getIdMetodoPago() + " - " + var.getNombreMetodo());
        }
    }
}
